from __future__ import annotations

from backend.app.models.domain import Product, ProductSearchResult
from backend.app.providers.product_provider import ProductProvider
from backend.app.utils.ids import new_id
from backend.app.utils.search_query import meaningful_search_tokens, normalize_persian_text


def _build_catalog() -> list[Product]:
    """Static demo catalog — diverse categories for mock search and recommendations."""
    return [
        # --- Keyboards ---
        Product(
            id=new_id(),
            title="کیبورد گیمینگ مکانیکی ردراگون مدل K552 Kumara",
            title_en="Redragon K552 Kumara Mechanical Keyboard",
            image_url="https://placehold.co/480x480/png?text=Redragon+K552",
            price=2_850_000,
            currency="IRR",
            rating=4.5,
            review_count=234,
            product_url="https://www.digikala.com/product/dkp-mock-k552/",
            source="digikala",
            available=True,
            description="کیبورد مکانیکی گیمینگ با سوئیچ قرمز و نورپردازی — گزینه متعادل برای استفاده روزانه و بازی.",
            highlights=["گیمینگ", "مکانیکی", "RGB"],
        ),
        Product(
            id=new_id(),
            title="کیبورد گیمینگ گرین مدل GK601-RGB",
            title_en="Green GK601 RGB Gaming Keyboard",
            image_url="https://placehold.co/480x480/png?text=Green+GK601",
            price=1_950_000,
            currency="IRR",
            rating=4.2,
            review_count=118,
            product_url="https://www.digikala.com/product/dkp-mock-gk601/",
            source="digikala",
            available=True,
            description="گزینه اقتصادی با نورپردازی RGB برای بودجه‌های محدودتر.",
            highlights=["گیمینگ", "RGB", "اقتصادی"],
        ),
        Product(
            id=new_id(),
            title="کیبورد گیمینگ لاجیتک مدل G213 Prodigy",
            title_en="Logitech G213 Prodigy",
            image_url="https://placehold.co/480x480/png?text=Logitech+G213",
            price=3_400_000,
            currency="IRR",
            rating=4.6,
            review_count=310,
            product_url="https://www.digikala.com/product/dkp-mock-g213/",
            source="digikala",
            available=True,
            description="کیبورد پریمیوم‌تر با برند معتبر و امتیاز بالا برای استفاده طولانی.",
            highlights=["گیمینگ", "پریمیوم"],
        ),
        Product(
            id=new_id(),
            title="کیبورد بی‌سیم اپل Magic Keyboard",
            title_en="Apple Magic Keyboard",
            image_url="https://placehold.co/480x480/png?text=Magic+Keyboard",
            price=5_200_000,
            currency="IRR",
            rating=4.7,
            review_count=156,
            product_url="https://www.digikala.com/product/dkp-mock-magic-kb/",
            source="digikala",
            available=True,
            description="کیبورد بی‌سیم باریک برای مک‌بوک و آی‌پد — طراحی مینیمال و باتری طولانی.",
            highlights=["بی‌سیم", "اپل", "اداری"],
        ),
        # --- Mice ---
        Product(
            id=new_id(),
            title="ماوس گیمینگ ریزر مدل DeathAdder Essential",
            title_en="Razer DeathAdder Essential",
            image_url="https://placehold.co/480x480/png?text=Razer+DeathAdder",
            price=1_750_000,
            currency="IRR",
            rating=4.7,
            review_count=402,
            product_url="https://www.digikala.com/product/dkp-mock-deathadder/",
            source="digikala",
            available=True,
            description="ماوس گیمینگ محبوب با ارگونومی خوب و امتیاز بالا.",
            highlights=["گیمینگ", "ارگونومیک"],
        ),
        Product(
            id=new_id(),
            title="ماوس بی‌سیم لاجیتک MX Master 3S",
            title_en="Logitech MX Master 3S Wireless Mouse",
            image_url="https://placehold.co/480x480/png?text=MX+Master+3S",
            price=4_800_000,
            currency="IRR",
            rating=4.8,
            review_count=287,
            product_url="https://www.digikala.com/product/dkp-mock-mxmaster/",
            source="digikala",
            available=True,
            description="ماوس حرفه‌ای برای طراحی و برنامه‌نویسی با اسکرول دقیق و چند دستگاه.",
            highlights=["بی‌سیم", "اداری", "پریمیوم"],
        ),
        Product(
            id=new_id(),
            title="ماوس گیمینگ ردراگون M711 Cobra",
            title_en="Redragon M711 Cobra Gaming Mouse",
            image_url="https://placehold.co/480x480/png?text=Redragon+M711",
            price=1_350_000,
            currency="IRR",
            rating=4.3,
            review_count=198,
            product_url="https://www.digikala.com/product/dkp-mock-m711/",
            source="digikala",
            available=True,
            description="ماوس گیمینگ اقتصادی با DPI قابل تنظیم و نورپردازی.",
            highlights=["گیمینگ", "اقتصادی", "RGB"],
        ),
        # --- Headphones & audio ---
        Product(
            id=new_id(),
            title="هدفون بی‌سیم سونی مدل WH-CH520",
            title_en="Sony WH-CH520 Wireless Headphones",
            image_url="https://placehold.co/480x480/png?text=Sony+WH-CH520",
            price=2_200_000,
            currency="IRR",
            rating=4.4,
            review_count=189,
            product_url="https://www.digikala.com/product/dkp-mock-whch520/",
            source="digikala",
            available=True,
            description="هدفون بی‌سیم سبک برای استفاده روزمره و هدیه.",
            highlights=["بی‌سیم", "هدیه"],
        ),
        Product(
            id=new_id(),
            title="هدفون گیمینگ هایپراکس مدل Cloud II",
            title_en="HyperX Cloud II Gaming Headset",
            image_url="https://placehold.co/480x480/png?text=HyperX+Cloud+II",
            price=3_600_000,
            currency="IRR",
            rating=4.6,
            review_count=445,
            product_url="https://www.digikala.com/product/dkp-mock-cloud2/",
            source="digikala",
            available=True,
            description="هدست گیمینگ با میکروفون جداشونده و راحتی بالا برای سشن‌های طولانی.",
            highlights=["گیمینگ", "هدست", "میکروفون"],
        ),
        Product(
            id=new_id(),
            title="ایربادز سامسونگ Galaxy Buds FE",
            title_en="Samsung Galaxy Buds FE",
            image_url="https://placehold.co/480x480/png?text=Galaxy+Buds+FE",
            price=3_100_000,
            currency="IRR",
            rating=4.5,
            review_count=312,
            product_url="https://www.digikala.com/product/dkp-mock-budsfe/",
            source="digikala",
            available=True,
            description="ایربادز بی‌سیم با نویزکنسلینگ فعال و کیف صندوق شارژ.",
            highlights=["بی‌سیم", "ایرباد", "نویزکنسلینگ"],
        ),
        Product(
            id=new_id(),
            title="اسپیکر بلوتوثی JBL Flip 6",
            title_en="JBL Flip 6 Portable Bluetooth Speaker",
            image_url="https://placehold.co/480x480/png?text=JBL+Flip+6",
            price=4_500_000,
            currency="IRR",
            rating=4.7,
            review_count=178,
            product_url="https://www.digikala.com/product/dkp-mock-jblflip/",
            source="digikala",
            available=True,
            description="اسپیکر قابل حمل ضدآب برای پیکنیک و مهمانی.",
            highlights=["بلوتوث", "قابل حمل", "ضدآب"],
        ),
        # --- Laptops ---
        Product(
            id=new_id(),
            title="لپ‌تاپ ایسوس VivoBook 15 X1504VA",
            title_en="ASUS VivoBook 15 X1504VA Laptop",
            image_url="https://placehold.co/480x480/png?text=ASUS+VivoBook",
            price=28_500_000,
            currency="IRR",
            rating=4.3,
            review_count=89,
            product_url="https://www.digikala.com/product/dkp-mock-vivobook/",
            source="digikala",
            available=True,
            description="لپ‌تاپ ۱۵ اینچی برای کار اداری و دانشجویی با Core i5 و ۸GB RAM.",
            highlights=["لپ‌تاپ", "اداری", "دانشجویی"],
        ),
        Product(
            id=new_id(),
            title="لپ‌تاپ گیمینگ لنوو Legion 5 Pro",
            title_en="Lenovo Legion 5 Pro Gaming Laptop",
            image_url="https://placehold.co/480x480/png?text=Legion+5+Pro",
            price=62_000_000,
            currency="IRR",
            rating=4.6,
            review_count=54,
            product_url="https://www.digikala.com/product/dkp-mock-legion/",
            source="digikala",
            available=True,
            description="لپ‌تاپ گیمینگ با RTX 4060 و نمایشگر 165Hz برای بازی‌های AAA.",
            highlights=["لپ‌تاپ", "گیمینگ", "RTX"],
        ),
        Product(
            id=new_id(),
            title="مک‌بوک ایر M2 13 اینچ 256GB",
            title_en="Apple MacBook Air M2 13-inch 256GB",
            image_url="https://placehold.co/480x480/png?text=MacBook+Air+M2",
            price=58_000_000,
            currency="IRR",
            rating=4.8,
            review_count=127,
            product_url="https://www.digikala.com/product/dkp-mock-mba-m2/",
            source="digikala",
            available=True,
            description="لپ‌تاپ سبک اپل با تراشه M2 — عالی برای برنامه‌نویسی و طراحی.",
            highlights=["لپ‌تاپ", "اپل", "سبک"],
        ),
        Product(
            id=new_id(),
            title="لپ‌تاپ HP Pavilion 14-dv2000",
            title_en="HP Pavilion 14-dv2000 Laptop",
            image_url="https://placehold.co/480x480/png?text=HP+Pavilion",
            price=22_000_000,
            currency="IRR",
            rating=4.1,
            review_count=67,
            product_url="https://www.digikala.com/product/dkp-mock-hp-pavilion/",
            source="digikala",
            available=True,
            description="لپ‌تاپ ۱۴ اینچی اقتصادی برای کارهای روزمره و وب.",
            highlights=["لپ‌تاپ", "اقتصادی", "سبک"],
        ),
        # --- Smartphones ---
        Product(
            id=new_id(),
            title="گوشی سامسونگ Galaxy A55 5G",
            title_en="Samsung Galaxy A55 5G",
            image_url="https://placehold.co/480x480/png?text=Galaxy+A55",
            price=18_500_000,
            currency="IRR",
            rating=4.4,
            review_count=523,
            product_url="https://www.digikala.com/product/dkp-mock-a55/",
            source="digikala",
            available=True,
            description="میان‌رده محبوب سامسونگ با دوربین 50MP و باتری 5000mAh.",
            highlights=["گوشی", "سامسونگ", "5G"],
        ),
        Product(
            id=new_id(),
            title="گوشی شیائومی Redmi Note 13 Pro",
            title_en="Xiaomi Redmi Note 13 Pro",
            image_url="https://placehold.co/480x480/png?text=Redmi+Note+13",
            price=14_200_000,
            currency="IRR",
            rating=4.3,
            review_count=891,
            product_url="https://www.digikala.com/product/dkp-mock-redmi13/",
            source="digikala",
            available=True,
            description="گوشی اقتصادی با شارژ 67W و AMOLED 120Hz.",
            highlights=["گوشی", "شیائومی", "اقتصادی"],
        ),
        Product(
            id=new_id(),
            title="آیفون 15 128GB",
            title_en="Apple iPhone 15 128GB",
            image_url="https://placehold.co/480x480/png?text=iPhone+15",
            price=52_000_000,
            currency="IRR",
            rating=4.7,
            review_count=234,
            product_url="https://www.digikala.com/product/dkp-mock-iphone15/",
            source="digikala",
            available=True,
            description="آیفون ۱۵ با Dynamic Island و USB-C — پرچمدار اپل.",
            highlights=["گوشی", "اپل", "پریمیوم"],
        ),
        Product(
            id=new_id(),
            title="گوشی پوکو X6 Pro 5G",
            title_en="Poco X6 Pro 5G",
            image_url="https://placehold.co/480x480/png?text=Poco+X6+Pro",
            price=16_800_000,
            currency="IRR",
            rating=4.5,
            review_count=412,
            product_url="https://www.digikala.com/product/dkp-mock-pocox6/",
            source="digikala",
            available=True,
            description="گوشی گیمینگ با Dimensity 8300 و شارژ 67W.",
            highlights=["گوشی", "گیمینگ", "5G"],
        ),
        # --- Monitors ---
        Product(
            id=new_id(),
            title="مانیتور سامسونگ 27 اینچ Odyssey G5",
            title_en="Samsung 27-inch Odyssey G5 Monitor",
            image_url="https://placehold.co/480x480/png?text=Odyssey+G5",
            price=12_500_000,
            currency="IRR",
            rating=4.5,
            review_count=156,
            product_url="https://www.digikala.com/product/dkp-mock-odyssey/",
            source="digikala",
            available=True,
            description="مانیتور گیمینگ 144Hz منحنی QHD برای FPS و MOBA.",
            highlights=["مانیتور", "گیمینگ", "144Hz"],
        ),
        Product(
            id=new_id(),
            title="مانیتور LG 24MP400 24 اینچ",
            title_en="LG 24MP400 24-inch Monitor",
            image_url="https://placehold.co/480x480/png?text=LG+24MP400",
            price=6_800_000,
            currency="IRR",
            rating=4.2,
            review_count=203,
            product_url="https://www.digikala.com/product/dkp-mock-lg24/",
            source="digikala",
            available=True,
            description="مانیتور Full HD اقتصادی برای دفتر و خانه.",
            highlights=["مانیتور", "اداری", "اقتصادی"],
        ),
        Product(
            id=new_id(),
            title="مانیتور Dell UltraSharp U2723QE 27 اینچ 4K",
            title_en="Dell UltraSharp U2723QE 27-inch 4K Monitor",
            image_url="https://placehold.co/480x480/png?text=Dell+U2723QE",
            price=28_000_000,
            currency="IRR",
            rating=4.8,
            review_count=78,
            product_url="https://www.digikala.com/product/dkp-mock-dell4k/",
            source="digikala",
            available=True,
            description="مانیتور 4K IPS برای طراحی گرافیک و ویرایش ویدیو.",
            highlights=["مانیتور", "4K", "طراحی"],
        ),
        # --- Tablets & wearables ---
        Product(
            id=new_id(),
            title="تبلت سامسونگ Galaxy Tab S9 FE",
            title_en="Samsung Galaxy Tab S9 FE",
            image_url="https://placehold.co/480x480/png?text=Tab+S9+FE",
            price=19_500_000,
            currency="IRR",
            rating=4.4,
            review_count=145,
            product_url="https://www.digikala.com/product/dkp-mock-tabs9/",
            source="digikala",
            available=True,
            description="تبلت ۱۰.۹ اینچی با S Pen برای یادداشت‌برداری و مطالعه.",
            highlights=["تبلت", "S Pen", "آموزشی"],
        ),
        Product(
            id=new_id(),
            title="آیپد 10.9 اینچ 64GB WiFi",
            title_en="Apple iPad 10.9-inch 64GB WiFi",
            image_url="https://placehold.co/480x480/png?text=iPad+10.9",
            price=24_000_000,
            currency="IRR",
            rating=4.6,
            review_count=198,
            product_url="https://www.digikala.com/product/dkp-mock-ipad/",
            source="digikala",
            available=True,
            description="آیپد پایه برای مطالعه، ویدیو و کارهای سبک.",
            highlights=["تبلت", "اپل", "آموزشی"],
        ),
        Product(
            id=new_id(),
            title="ساعت هوشمند اپل Watch SE 2nd Gen",
            title_en="Apple Watch SE 2nd Generation",
            image_url="https://placehold.co/480x480/png?text=Apple+Watch+SE",
            price=12_000_000,
            currency="IRR",
            rating=4.5,
            review_count=167,
            product_url="https://www.digikala.com/product/dkp-mock-watchse/",
            source="digikala",
            available=True,
            description="ساعت هوشمند برای فیتنس و نوتیفیکیشن — گزینه اقتصادی اپل.",
            highlights=["ساعت هوشمند", "فیتنس", "اپل"],
        ),
        Product(
            id=new_id(),
            title="مچ‌بند هوشمند شیائومی Mi Band 8",
            title_en="Xiaomi Mi Band 8",
            image_url="https://placehold.co/480x480/png?text=Mi+Band+8",
            price=1_800_000,
            currency="IRR",
            rating=4.4,
            review_count=678,
            product_url="https://www.digikala.com/product/dkp-mock-miband/",
            source="digikala",
            available=True,
            description="مچ‌بند ارزان با پایش ضربان قلب و خواب.",
            highlights=["مچ‌بند", "فیتنس", "اقتصادی"],
        ),
        # --- Storage & accessories ---
        Product(
            id=new_id(),
            title="SSD سامسونگ 990 Pro 1TB NVMe",
            title_en="Samsung 990 Pro 1TB NVMe SSD",
            image_url="https://placehold.co/480x480/png?text=990+Pro+1TB",
            price=5_500_000,
            currency="IRR",
            rating=4.8,
            review_count=289,
            product_url="https://www.digikala.com/product/dkp-mock-990pro/",
            source="digikala",
            available=True,
            description="SSD NVMe پرسرعت Gen4 برای گیمینگ و ویرایش ویدیو.",
            highlights=["SSD", "NVMe", "ذخیره‌سازی"],
        ),
        Product(
            id=new_id(),
            title="فلش مموری SanDisk Ultra Dual Drive 128GB",
            title_en="SanDisk Ultra Dual Drive 128GB",
            image_url="https://placehold.co/480x480/png?text=SanDisk+128GB",
            price=850_000,
            currency="IRR",
            rating=4.3,
            review_count=445,
            product_url="https://www.digikala.com/product/dkp-mock-sandisk/",
            source="digikala",
            available=True,
            description="فلش USB-C و USB-A برای انتقال فایل بین موبایل و لپ‌تاپ.",
            highlights=["فلش", "USB-C", "قابل حمل"],
        ),
        Product(
            id=new_id(),
            title="پاوربانک انکر PowerCore 20000mAh",
            title_en="Anker PowerCore 20000mAh Power Bank",
            image_url="https://placehold.co/480x480/png?text=Anker+PowerCore",
            price=1_650_000,
            currency="IRR",
            rating=4.6,
            review_count=534,
            product_url="https://www.digikala.com/product/dkp-mock-anker/",
            source="digikala",
            available=True,
            description="پاوربانک با دو پورت USB و شارژ سریع برای سفر.",
            highlights=["پاوربانک", "شارژ", "سفر"],
        ),
        Product(
            id=new_id(),
            title="هاب USB-C Baseus 7-in-1",
            title_en="Baseus 7-in-1 USB-C Hub",
            image_url="https://placehold.co/480x480/png?text=Baseus+Hub",
            price=1_200_000,
            currency="IRR",
            rating=4.2,
            review_count=312,
            product_url="https://www.digikala.com/product/dkp-mock-baseus/",
            source="digikala",
            available=True,
            description="هاب USB-C با HDMI، USB 3.0 و کارت‌خوان SD.",
            highlights=["هاب", "USB-C", "لپ‌تاپ"],
        ),
        # --- Networking & peripherals ---
        Product(
            id=new_id(),
            title="روتر TP-Link Archer AX73 WiFi 6",
            title_en="TP-Link Archer AX73 WiFi 6 Router",
            image_url="https://placehold.co/480x480/png?text=Archer+AX73",
            price=4_200_000,
            currency="IRR",
            rating=4.5,
            review_count=189,
            product_url="https://www.digikala.com/product/dkp-mock-tplink/",
            source="digikala",
            available=True,
            description="روتر WiFi 6 با پوشش مناسب برای خانه و گیمینگ آنلاین.",
            highlights=["روتر", "WiFi 6", "شبکه"],
        ),
        Product(
            id=new_id(),
            title="وب‌کم Logitech C920 HD Pro",
            title_en="Logitech C920 HD Pro Webcam",
            image_url="https://placehold.co/480x480/png?text=Logitech+C920",
            price=2_800_000,
            currency="IRR",
            rating=4.6,
            review_count=267,
            product_url="https://www.digikala.com/product/dkp-mock-c920/",
            source="digikala",
            available=True,
            description="وب‌کم Full HD برای جلسات آنلاین و استریم.",
            highlights=["وب‌کم", "Full HD", "استریم"],
        ),
        Product(
            id=new_id(),
            title="میکروفون Blue Yeti USB",
            title_en="Blue Yeti USB Microphone",
            image_url="https://placehold.co/480x480/png?text=Blue+Yeti",
            price=5_800_000,
            currency="IRR",
            rating=4.7,
            review_count=198,
            product_url="https://www.digikala.com/product/dkp-mock-yeti/",
            source="digikala",
            available=True,
            description="میکروفون USB حرفه‌ای برای پادکست و استریم.",
            highlights=["میکروفون", "استریم", "پادکست"],
        ),
        # --- Home & lifestyle ---
        Product(
            id=new_id(),
            title="تلویزیون سامسونگ 55 اینچ Crystal UHD 4K",
            title_en="Samsung 55-inch Crystal UHD 4K TV",
            image_url="https://placehold.co/480x480/png?text=Samsung+55+TV",
            price=32_000_000,
            currency="IRR",
            rating=4.4,
            review_count=112,
            product_url="https://www.digikala.com/product/dkp-mock-samsung-tv/",
            source="digikala",
            available=True,
            description="تلویزیون 4K 55 اینچی با Tizen برای فیلم و بازی کنسول.",
            highlights=["تلویزیون", "4K", "خانگی"],
        ),
        Product(
            id=new_id(),
            title="دستگاه تصفیه هوا Xiaomi Mi Air Purifier 4",
            title_en="Xiaomi Mi Air Purifier 4",
            image_url="https://placehold.co/480x480/png?text=Mi+Air+Purifier",
            price=8_500_000,
            currency="IRR",
            rating=4.5,
            review_count=234,
            product_url="https://www.digikala.com/product/dkp-mock-purifier/",
            source="digikala",
            available=True,
            description="تصفیه‌کننده هوا برای اتاق خواب و محیط‌های آلوده.",
            highlights=["تصفیه هوا", "خانگی", "سلامت"],
        ),
        Product(
            id=new_id(),
            title="ماشین espresso دلونگی Dedica EC685",
            title_en="DeLonghi Dedica EC685 Espresso Machine",
            image_url="https://placehold.co/480x480/png?text=DeLonghi+Dedica",
            price=18_000_000,
            currency="IRR",
            rating=4.6,
            review_count=89,
            product_url="https://www.digikala.com/product/dkp-mock-dedica/",
            source="digikala",
            available=True,
            description="ماشین espresso باریک برای آشپزخانه کوچک — هدیه مناسب.",
            highlights=["قهوه", "آشپزخانه", "هدیه"],
        ),
        Product(
            id=new_id(),
            title="کوله‌پشتی لپ‌تاپ Samsonite Guardit 15.6",
            title_en="Samsonite Guardit 15.6 Laptop Backpack",
            image_url="https://placehold.co/480x480/png?text=Samsonite+Backpack",
            price=2_400_000,
            currency="IRR",
            rating=4.4,
            review_count=156,
            product_url="https://www.digikala.com/product/dkp-mock-samsonite/",
            source="digikala",
            available=True,
            description="کوله‌پشتی ضدآب با جای لپ‌تاپ ۱۵.۶ اینچ برای دانشجو و سفر.",
            highlights=["کوله", "لپ‌تاپ", "سفر"],
        ),
        Product(
            id=new_id(),
            title="کفش ورزشی نایک Air Max 270",
            title_en="Nike Air Max 270 Running Shoes",
            image_url="https://placehold.co/480x480/png?text=Nike+Air+Max",
            price=3_800_000,
            currency="IRR",
            rating=4.5,
            review_count=423,
            product_url="https://www.digikala.com/product/dkp-mock-nike/",
            source="digikala",
            available=True,
            description="کفش ورزشی راحت برای دویدن و پیاده‌روی روزانه.",
            highlights=["کفش", "ورزشی", "نایک"],
        ),
        Product(
            id=new_id(),
            title="کتاب «Atomic Habits» جیمز کلیر",
            title_en="Atomic Habits by James Clear (Persian Edition)",
            image_url="https://placehold.co/480x480/png?text=Atomic+Habits",
            price=320_000,
            currency="IRR",
            rating=4.9,
            review_count=1245,
            product_url="https://www.digikala.com/product/dkp-mock-atomic-habits/",
            source="digikala",
            available=True,
            description="پرفروش‌ترین کتاب خودیاری — هدیه مناسب برای عید و تولد.",
            highlights=["کتاب", "خودیاری", "هدیه"],
        ),
    ]


def _product_search_text(product: Product) -> str:
    return normalize_persian_text(
        " ".join(
            [
                product.title,
                product.title_en,
                product.description,
                " ".join(product.highlights),
            ]
        ).lower()
    )


class MockProductProvider(ProductProvider):
    name = "mock"

    def __init__(self) -> None:
        self._catalog = _build_catalog()

    async def search(self, query: str, max_results: int = 5) -> ProductSearchResult:
        tokens = meaningful_search_tokens(query)
        if not tokens:
            return ProductSearchResult(
                products=[],
                query=query,
                provider=self.name,
                total_found=0,
            )

        scored: list[tuple[int, Product]] = []
        for product in self._catalog:
            haystack = _product_search_text(product)
            score = sum(1 for token in tokens if token in haystack)
            if score > 0:
                scored.append((score, product))

        scored.sort(key=lambda item: (-item[0], -item[1].rating, -item[1].review_count))
        final = [product for _, product in scored[:max_results]]
        return ProductSearchResult(
            products=final,
            query=query,
            provider=self.name,
            total_found=len(final),
        )
